version: "3.7"

networks:
  teamleader.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    container_name: teamleader.php
    tty: true
    user: 1000:1000
    networks:
      - teamleader.network
    volumes:
      - .:/var/www

  nginx:
    build: ./docker/nginx
    container_name: teamleader.nginx
    tty: true
    depends_on:
      - php
    ports:
      - "433:433"
      - "80:80"
    networks:
      - teamleader.network
    volumes:
      - .:/var/www
